services:
  movie_bot:
    build: .
    container_name: movie_bot
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ./movies.db:/app/movies.db
    environment:
      - TZ=Europe/London
